/**
 * avatanel — EvoLoop Evolution Types
 *
 * TypeScript schemas for the EvoLoop self-improvement pipeline:
 *   - PendingRule          — behavior rule candidates (.learnings/pending/rules.json)
 *   - InfoSource           — external information sources (.learnings/pending/info-sources.json)
 *   - PendingExpressionEvent — dialog reasoning event candidates
 *   - PendingMissionEvent    — task execution event candidates
 *   - PendingSkill         — reviewed skill candidates (.skills/pending/<name>.md)
 *   - ReviewLogEntry       — daily-review audit log
 *
 * All "pending" types must pass through cron review before being promoted
 * to formal knowledge files. See docs/architecture/architecture.md.
 */

// ─── Behavior Rule (──.learnings/pending/rules.json) ─────────────────────────

export type PendingStatus = 'pending' | 'approved' | 'rejected' | 'archived';

export type RuleSource =
  | 'reflection'        // historical/manual reflection import source
  | 'pattern-tracker'   // generated from PatternTracker hits
  | 'info-source'       // distilled from external info-sources cron
  | 'unified-extraction' // [P3] generated by the unified memory extractor pipeline
  | 'manual';           // user-injected

export interface PendingRule {
  /** Stable id, e.g. "pending_20260416_001" */
  id: string;
  /** Origin classification */
  source: RuleSource;
  /** Free-form context describing the trigger (which session, which prompt) */
  source_detail: string;
  /** ISO 8601 timestamp */
  created_at: string;
  /** The rule body itself, in plain language */
  content: string;
  /** Why the rule was proposed */
  reason: string;
  /** Where the rule should be promoted on approval (e.g. [".learnings/LEARNINGS.md"]) */
  target_files: string[];
  /** Lifecycle status */
  status: PendingStatus;
  /** ISO timestamp of cron review, "" until reviewed */
  reviewed_at: string;
  /** Reviewer's notes on approve/reject decision */
  review_note: string;
}

export interface PendingRulesFile {
  version: string; // YYYY-MM-DD when the file was first created
  rules: PendingRule[];
}

// ─── External Information Sources (.learnings/pending/info-sources.json) ────

export type InfoSourceKind = 'rss' | 'url' | 'x' | 'github' | 'custom';

export interface InfoSource {
  /** Display name */
  name: string;
  /** RSS URL / page URL / X handle / GitHub repo etc. */
  instructions: string;
  /** Source type — drives which fetcher is used */
  kind: InfoSourceKind;
  /** Whether the cron should poll this source */
  enabled: boolean;
  /** Free-form: what to look for / what kind of rules to extract */
  focus: string;
  /** ISO timestamp when added */
  added_at: string;
}

export interface InfoSourcesFile {
  version: string;
  sources: InfoSource[];
}

// ─── Expression / Mission Pending Events ─────────────────────────────────────

export type PendingEventType = 'expression' | 'mission';

export interface PendingExpressionEvent {
  ts: string;
  type: 'expression';
  signal: string;       // "weak-negative: user repeated same question"
  attribution: string;  // "EXPRESSION → Strategy"
  content: string;      // proposed rule text
  source: string;       // "session=discord-ch-X-u-Y, turn 7"
}

export interface PendingMissionEvent {
  ts: string;
  type: 'mission';
  signal: string;
  attribution: string;
  content: string;
  source: string;
}

export type PendingEvent = PendingExpressionEvent | PendingMissionEvent;

// ─── Pending Skill (.skills/pending/<name>.md) ───────────────────────────────

export interface PendingSkillFrontmatter {
  name: string;
  description: string;
  category?: string;
  /** Always 'pending' until cron review approves */
  status: PendingStatus;
  source: RuleSource;
  source_detail: string;
  created_at: string;
  /** ISO timestamp set by reviewer */
  reviewed_at?: string;
  /** Reviewer's notes */
  review_note?: string;
}

/** A pending skill on disk has the frontmatter above plus the SKILL.md body. */
export interface PendingSkill {
  frontmatter: PendingSkillFrontmatter;
  body: string;
}

// ─── Pending writer / staging interfaces ───────────────────────────────────

export interface PendingWriter {
  appendPendingRule(
    rule: Omit<PendingRule, 'id' | 'created_at' | 'status' | 'reviewed_at' | 'review_note'> & {
      id?: string;
    },
  ): string;
  appendPendingExpression(event: Omit<PendingExpressionEvent, 'ts' | 'type'>): void;
  appendPendingMission(event: Omit<PendingMissionEvent, 'ts' | 'type'>): void;
  writePendingSkill(skill: PendingSkill): string;
}

export interface PendingSkillCatalog {
  listPendingSkills(): string[];
  listActiveSkills(): string[];
}

export type PendingSkillSink = PendingWriter & PendingSkillCatalog;

export interface StagingLayout {
  sessionId: string;
  sessionDir: string;
  root: string;
  rulesPath: string;
  expressionPath: string;
  missionsPath: string;
  skillsDir: string;
}

export interface SessionStagingEntry {
  sessionId: string;
  root: string;
  state: 'live' | 'snapshot';
}

export interface PromotionCounts {
  rules: number;
  expression: number;
  mission: number;
  skills: number;
}

export interface PromotionSummary {
  sourceRoot: string;
  promoted: PromotionCounts;
  skipped: PromotionCounts;
  errors: string[];
  cleared: boolean;
}

// ─── Review Log (reviews/YYYY-MM-DD.md) ──────────────────────────────────────

export interface ReviewLogEntry {
  /** ISO timestamp */
  ts: string;
  /** Which queue: rules, expression, mission, skills */
  queue: 'rules' | 'expression' | 'mission' | 'skills';
  /** ID or name of the item reviewed */
  itemId: string;
  /** Decision */
  decision: 'approved' | 'rejected' | 'archived';
  /** Reviewer LLM model name */
  reviewer: string;
  /** Reviewer's reasoning */
  note: string;
  /** Where the item ended up if approved (file path) */
  promotedTo?: string;
}

// ─── Workspace Metadata ──────────────────────────────────────────────────────

/**
 * Per-userId workspace layout. Created on first agent boot for that user.
 * Path resolution lives in workspace.ts; this interface just documents the shape.
 */
export interface AgentWorkspaceLayout {
  /** Root: ~/.avatanel/user/<userId>/ or ~/.avatanel/user/<userId>/agents/<agentName>/ */
  root: string;

  // Legacy identity files. Current persona truth lives in PersonaStore and
  // runtime prompt assembly; these paths are kept for migration/indexing.
  soulMd: string;
  identityMd: string;
  userMd: string;

  // Legacy operations stub. Workspace bootstrap no longer creates it; keep the
  // path for compatibility/migration. Repo-level CLAUDE.md + docs are the
  // human-facing operations source of truth.
  claudeMd: string;

  // Phase definitions
  expressionMd: string;
  missionMd: string;
  reflectionMd: string;
  sanitizeRulesMd: string;

  // Legacy MEMORY.md path plus legacy daily memory directory. Current
  // long-term memory truth lives in SQLite + vectors; new workspaces do not
  // create these paths, and HistoryIndex no longer indexes memory/*.md.
  memoryMd: string;
  memoryDir: string;          // memory/

  // Sessions
  sessionsDir: string;        // sessions/

  // Learning layer
  learningsDir: string;       // .learnings/
  errorsMd: string;           // .learnings/ERRORS.md
  learningsMd: string;        // .learnings/LEARNINGS.md
  pendingRulesPath: string;   // .learnings/pending/rules.json
  infoSourcesPath: string;    // .learnings/pending/info-sources.json

  expressionDir: string;      // .expression/
  expressionRulesMd: string;  // .expression/rules.md
  expressionExamplesMd: string; // .expression/examples.md
  expressionPendingDir: string;  // .expression/pending/

  missionsDir: string;        // .missions/
  executionPatternsMd: string;     // .missions/execution-patterns.md
  executionAntipatternsMd: string; // .missions/execution-antipatterns.md
  missionsPendingDir: string;       // .missions/pending/

  // Skills (per-agent — replaces global ~/.avatanel/skills/)
  skillsDir: string;          // .skills/
  skillsActiveDir: string;    // .skills/active/  ← SkillStore loads from here
  skillsPendingDir: string;   // .skills/pending/
  skillsArchiveDir: string;   // .skills/archive/

  // Reviews log
  reviewsDir: string;         // reviews/

  // Context
  contextDir: string;         // context/
}
